# forums
forum_latest_topics:
  url:  /forums/latest-topics
  param: { module: sfSimpleForum, action: latestTopics }

forum_latest_posts:
  url:  /forums/latest-posts
  param: { module: sfSimpleForum, action: latestPosts }

forum_home:
  url:  /forums
  param: { module: sfSimpleForum, action: index }

forum_home_list:
  url:  /forums
  param: { module: sfSimpleForum, action: forumList }

forum_name:
  url:  /forums/:forum_name
  param: { module: sfSimpleForum, action: forum }

forum_name_last:
  url:  /forums/:forum_name/lastest-posts
  param: { module: sfSimpleForum, action: forumLatestPosts }

forum_topic:
  url:  /forums/topic,:id,:stripped_title
  param: { module: sfSimpleForum, action: topic }

forum_message:
  url:  /forums/view-post/:id
  param: { module: sfSimpleForum, action: post }

forum_new_topic:
  url:  /forums/new-topic/:forum_name
  param: { module: sfSimpleForum, action: createTopic }

forum_user:
  url:  /user/:username/posts
  param: { module: sfSimpleForum, action: userLatestPosts }

forum_user_topics:
  url:  /user/:username/topics
  param: { module: sfSimpleForum, action: userLatestTopics }