sfSimpleForumCategory:
  actAs:
    Timestampable:
    Sluggable:
      fields:         [name]
  columns:
    name:             string(255)
    description:      clob
    rank:             integer
    
sfSimpleForumForum:
  actAs:
    Timestampable:
    Sluggable:
      fields:         [name]
  columns:
    name:             string(255)
    description:      clob
    rank:             integer
    category_id:      integer
    latest_post_id:   integer
    nb_posts:         integer
    nb_topics:        integer
    phpbb_id:         integer
  relations:
    sfSimpleForumCategory: 
      local:          category_id
      foreign:        id
      type:           one
      onDelete:       CASCADE
    sfSimpleForumPost: 
      local:          latest_post_id
      foreign:        id
      type:           one
      onDelete:       SET NULL
    
sfSimpleForumTopic:
  actAs:
    Timestampable:
    Sluggable:
      fields:         [title]
  columns:
    title:            string(255)
    is_sticked:
      type:           boolean
      default:        0
    is_locked:
      type:           boolean
      default:        0
    forum_id:         integer
    latest_post_id:   integer
    user_id:          integer
    nb_posts:
      type:           integer
      default:        0
    nb_views:
      type:           integer
      default:        0
    nb_recommandations:
      type:           integer
      default:        0
    phpbb_id:         integer
  relations:
    sfSimpleForumForum: 
      local:          forum_id
      foreign:        id
      type:           one
      onDelete:       CASCADE
    sfSimpleForumPost: 
      local:          latest_post_id
      foreign:        id
      type:           one
      onDelete:       SET NULL
    sfGuardUser: 
      local:          user_id
      foreign:        id
      type:           one
      onDelete:       SET NULL
    
sfSimpleForumPost:
  actAs:
    Timestampable:
  columns:
    title:            string(255)
    content:          clob
    topic_id:         integer
    user_id:          integer
    forum_id:         integer
    author_name:      string(255)
    phpbb_id:         integer
  relations:
    sfSimpleForumForum: 
      local:          forum_id
      foreign:        id
      type:           one
      onDelete:       CASCADE
    sfSimpleForumTopic: 
      local:          topic_id
      foreign:        id
      type:           one
      onDelete:       CASCADE
    sfGuardUser: 
      local:          user_id
      foreign:        id
      type:           one
      onDelete:       CASCADE

sfSimpleAbuseLog:
  actAs:
    Timestampable:
  columns:
    user_id:
      type: integer
      primary: true
    topic_id:
      type: integer
      primary: true
  relations:
    sfGuardUser: 
      local:          user_id
      foreign:        id
      type:           one
      onDelete:       CASCADE
    sfSimpleForumTopic: 
      local:          topic_id
      foreign:        id
      type:           one
      onDelete:       CASCADE

sfSimpleRecommandationLog:
  actAs:
    Timestampable:
  columns:
    user_id:
      type: integer
      primary: true
    topic_id:
      type: integer
      primary: true
  relations:
    sfGuardUser: 
      local:          user_id
      foreign:        id
      type:           one
      onDelete:       CASCADE
    sfSimpleForumTopic: 
      local:          topic_id
      foreign:        id
      type:           one
      onDelete:       CASCADE

sfSimpleForumTopicView:
  actAs:
    Timestampable:
  columns:
    user_id:
      type:           integer
      primary:        true
    topic_id:
      type:           integer
      primary:        true
  relations:
    sfGuardUser: 
      local:          user_id
      foreign:        id
      type:           one
      onDelete:       CASCADE
    sfSimpleForumTopic: 
      local:          topic_id
      foreign:        id
      type:           one
      onDelete:       CASCADE
